[application]
name = "dioxus-todo-app"

[web.app]
title = "Dioxus Todo App"
base_path = "/"

[web.watcher]
watch_path = ["src", "assets"]
reload_html = true
index_on_404 = true

[web.resource]
style = ["assets/main.css"]

[bundler]
public_url = "/"

[[web.resource.script]]
src = "https://cdn.tailwindcss.com" 